### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by jagadeeshthegeek** [malkusch/amazon-ecs-api#5]
Hi Team,

When this line getting executed in main program,
`Items foundItems = api.getItemSearch().call(itemSearchRequest);`

I have got this below Exception. Could you please help me.

```
Exception in thread "main" de.malkusch.amazon.ecs.exception.RequestErrorException: Ihre Zugriffsschlüssel-ID ist nicht für das Produktwerbungs-API registriert. Verwenden Sie die Zugriffsschlüssel-ID, die Sie nach der Registrierung bei https://partnernet.amazon.de/gp/flex/advertising/api/sign-in.html erhalten haben.
	at de.malkusch.amazon.ecs.call.ApiCall.validateResponse(ApiCall.java:82)
	at de.malkusch.amazon.ecs.call.ApiCall.call(ApiCall.java:47)
	at com.jag.aws.MainClass.main(MainClass.java:40)


```

**Comment by jagadeeshthegeek** [comment]
This issue happened, Since i didn't register "Amazon Product Advertising API".

After registration, it works fine. Thanks!!
