### ISSUE TITLE
Can't get API call to function without HTTP error 400

### ISSUE THREAD

**Issue by oscarandjo** [malkusch/amazon-ecs-api#8]
Hi,

I've configured my properties correctly (as if I intentionally break my properties file I get a 403 forbidden error instead). I used the example you provided in the readme.

When it gets to the following line:
foundItems = api.getItemSearch().call(itemSearchRequest);

The program breaks with an exception error with 

`Exception in thread "main" com.sun.xml.internal.ws.client.ClientTransportException: The server sent HTTP status code 400: Bad Request
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.checkStatusCode(HttpTransportPipe.java:310)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.createResponsePacket(HttpTransportPipe.java:259)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:217)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:130)
	at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:95)
	at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Fiber.java:1121)
	at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Fiber.java:1035)
	at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Fiber.java:1004)
	at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Fiber.java:862)
	at com.sun.xml.internal.ws.client.Stub.process(Stub.java:448)
	at com.sun.xml.internal.ws.client.sei.SEIStub.doProcess(SEIStub.java:178)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:93)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
	at com.sun.proxy.$Proxy31.itemSearch(Unknown Source)
	at de.malkusch.amazon.ecs.call.ItemSeachCall.call(ItemSeachCall.java:25)
	at de.malkusch.amazon.ecs.call.ItemSeachCall.call(ItemSeachCall.java:14)
	at de.malkusch.amazon.ecs.call.ApiCall.callRequests(ApiCall.java:39)
	at de.malkusch.amazon.ecs.call.ApiCall.call(ApiCall.java:44)
	at ProductAccessApi.makeRequest(ProductAccessApi.java:54)
	at main.main(main.java:14)`

Any ideas why I may be getting this problem?

**Comment by aditya2592** [comment]
I am getting the same error

**Comment by aditya2592** [comment]
@oscarandjo This worked for me by setting the correct webendpoint for amazon (India in my case) : 

```
api = new ProductAdvertisingAPI(configuration, new AWSECommerceService().getAWSECommerceServicePortIN());
                
```

**Comment by oscarandjo** [comment]
Great, I'll give it a try. Thanks.

**Comment by oscarandjo** [comment]
Brilliant, it worked.

I just needed to change the DE to UK (as I copied the example).

Thanks so much Aditya
